Repository stephendawsondev/jedi-academy, pull requests merged in 2024-05, with the labels that each got.

#18 add page title
  index.html
Labels: pull request

#20 add background image, add dialog text
  assets/images/template.png
  css/style.css
  index.html
  js/script.js
Labels: pull request

#22 main story creation
  game_story.txt
Labels: pull request

#27 add new folder structure
  memory/memory.css
  memory/memory.html
  memory/memory.js
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
  wordle/wordle.css
  wordle/wordle.html
  wordle/wordle.js
Labels: pull request

#28 added images for games
  assets/images/Death_star.png
  assets/images/Yoda.webp
  assets/images/anakin-skywalker.webp
  assets/images/bb8-d0.jpeg
  assets/images/c3p0.jpeg
  assets/images/c3po-r2d2.png
  assets/images/jarjar.jpeg
  assets/images/leia-organa.jpeg
Labels: pull request

#34 Index wireframes
  README.md
  assets/wireframes/laptop-wireframe-index.png
  assets/wireframes/phone-wireframe-index.png
  assets/wireframes/tablet-wireframe-index.png
  public/ouchie-101soundboards.mp3
  public/r2d2-scream.mp3
  public/wrong-choice.mp3
  public/youngling-padawan.mp3
Labels: pull request

#32 added sounds for different games
  public/ouchie-101soundboards.mp3
  public/r2d2-scream.mp3
  public/wrong-choice.mp3
  public/youngling-padawan.mp3
Labels: pull request

#30 add local storage functionality
  js/script.js
Labels: pull request

#38 Added structure and styling to index.html
  assets/images/Jedi_Temple_spires_ROTS.png
  assets/images/home-page-image.png
  css/style.css
  fonts/index-font/Starjedi.ttf
  index.html
  js/script.js
Labels: pull request

#48 update local storage settings:
  index.html
  js/index.js
  js/script.js
Labels: pull request

#50 Results mockup
  README.md
  assets/wireframes/Results-laptop-view.png
  assets/wireframes/Results-tablet-view.png
  assets/wireframes/meet-the-team-laptop.png
  assets/wireframes/meet-the-team-phone.png
  assets/wireframes/meet-the-team-tablet.png
  assets/wireframes/results-phone-view.png
  memory/memory.js
Labels: pull request

#51 Memory flip game
  memory/memory.css
  memory/memory.html
  memory/memory.js
Labels: pull request

#53 add audio object, add audio buttons
  assets/images/music_off.webp
  assets/images/music_on.webp
  assets/images/sound_off.webp
  assets/images/sound_on.webp
  css/style.css
  index.html
  js/script.js
  public/ouchie.mp3
  whack-a-droid/assets/sounds/jawa-angry.mp3
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
Labels: enhancement, pull request

#54 Create what a droid game
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
Labels: pull request

#55 Game Board functions
  memory/memory.css
  memory/memory.html
Labels: pull request

#56 added memory game logic to memory.js
  memory/memory.js
Labels: pull request

#57 add sounds for memory game and meet the team
  public/councilors-meet.mp3
  public/r2r2-happy.mp3
  public/trial-memory-completion.mp3
Labels: pull request

#59 Create instructions modal
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
Labels: pull request

#61 added completion sounds to whackadroid and wordle games
  memory/assets/sounds/r2r2-happy.mp3
  whack-a-droid/assets/sounds/Complete-trial-agility.mp3
  wordle/assets/sounds/complete-wisdomTrial.mp3
Labels: pull request

#63 changed lockboard in memory.js
  memory/assets/sounds/r2d2-scream.mp3
  memory/memory.js
Labels: pull request

#64 update wordle game
  css/index.css
  css/style.css
  index.html
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
  wordle/assets/sounds/complete-wisdom-trial.mp3
  wordle/wordle.css
  wordle/wordle.html
  wordle/wordle.js
Labels: pull request

#65 remove commented out code
  memory/memory.js
Labels: pull request

#67 update wordle code
  css/style.css
  js/script.js
  memory/memory.css
  memory/memory.html
  wordle/wordle.css
  wordle/wordle.html
  wordle/wordle.js
Labels: pull request

#68 add whack-a-droid updates
  css/style.css
  js/script.js
  whack-a-droid/assets/images/lightsaber.png
  whack-a-droid/assets/sounds/smash-metal.mp3
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
Labels: pull request

#73 added style to buttons in index
  assets/images/graduation-ceremony.jpeg
  css/style.css
  index.html
  memory/memory.css
  memory/memory.html
  memory/memory.js
  results.html
Labels: pull request

#78 added results logic to results.js
  css/style.css
  index.html
  js/results.js
  js/script.js
  results.html
Labels: pull request

#80 style wordle dialog
  whack-a-droid/whack-a-droid.css
  wordle/assets/images/c3po.png
  wordle/assets/images/first-attempt.png
  wordle/assets/images/second-attempt.png
  wordle/assets/images/third-attempt.png
  wordle/wordle.css
  wordle/wordle.html
Labels: pull request

#81 Music main
  js/script.js
  public/starwars-battle-music.mp3
Labels: pull request

#82 added meet the team link to index.html and styled
  css/style.css
  index.html
  js/index.js
Labels: pull request

#83 added timer functionality to whack a droid and link for meet the team…
  index.html
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
Labels: pull request

#84 added youngling-padawan mp3 and code into script.js
  js/script.js
Labels: pull request

#88 make agility trial responsive
  js/script.js
  whack-a-droid/assets/images/tatooine.webp
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
Labels: enhancement, pull request

#90 team page content and styling
  memory/memory.html
  team-page/team-images/donald.jpeg
  team-page/team-images/george.png
  team-page/team-images/hannah.jpeg
  team-page/team-images/jedi-council-room.jpeg
  team-page/team-images/stephen.jpeg
  team-page/team-images/tharindu.jpeg
  team-page/team-images/towbie.png
  team-page/team-page.css
  team-page/team-page.html
  wordle/wordle.html
Labels: pull request

#91 fix link in team page
  css/style.css
  team-page/team-page.html
Labels: pull request

#92 make responsive changes
  css/style.css
  index.html
  results.html
  team-page/team-page.css
  whack-a-droid/whack-a-droid.css
  wordle/wordle.css
Labels: pull request

#93 tidy up
  index.html
  memory/memory.html
  memory/memory.js
  results.html
  team-page/team-page.html
  wordle/wordle.html
  wordle/wordle.js
Labels: pull request

#94 bug fixes
  css/style.css
  js/index.js
  js/results.js
  js/script.js
  memory/memory.css
  memory/memory.js
  whack-a-droid/whack-a-droid.css
  whack-a-droid/whack-a-droid.html
  whack-a-droid/whack-a-droid.js
  wordle/wordle.html
Labels: bug, pull request

#95 fix font bug
  team-page/team-page.html
Labels: pull request

#100 fix font bug in tharindi description
  team-page/team-page.html
Labels: pull request

#101 fix font bug and add towbie description to meet the team
  team-page/team-page.html
Labels: pull request

#102 update wordle tile colors and remove word 'leias' from word list
  wordle/wordle.css
  wordle/wordle.js
Labels: pull request

#106 insert screenshots to prpject
  assets/screenshots/1-home-page-screenshot.png
  assets/screenshots/10-wisdom-how-play.png
  assets/screenshots/11-home-how-play.png
  assets/screenshots/12-team-page.png
  assets/screenshots/13-results page.png
  assets/screenshots/2-enter-name-screenshot.png
  assets/screenshots/3-trial-selection.png
  assets/screenshots/4-memory-game.png
  assets/screenshots/5-memory-how-to-play.png
  assets/screenshots/6-agility-game.png
  assets/screenshots/7-agility-how-to-play.png
  assets/screenshots/8-agility-game-play.png
  assets/screenshots/9-wisdom-game.png
Labels: pull request

#109 added info and image to team page
  README.md
  memory/memory.css
  memory/memory.js
  team-page/team-images/towbie.jpeg
  team-page/team-page.html
Labels: pull request

#113 added to readme and media queries
  README.md
  css/style.css
Labels: pull request

#115 finish readme and remove any commented out code from all files
  README.md
  css/index.css
  css/style.css
  js/script.js
  team-page/team-page.html
  wordle/wordle.css
  wordle/wordle.html
Labels: pull request
